src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(RedirectView.as_view(url='posts/')), name='root'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Debug-toolbar setting
    import debug_toolbar
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

src/posts/urls.py
from django.urls import path

from . import views
from .views import PostListView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
    path('update/<int:id>/', views.post_update, name='post_update'),
]

src/templates/base.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>SNS Project</title>
</head>

<body>
<div class="container my-3">
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
            <span class="fs-4">Social Network App</span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Search</a>
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Feed</a>
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Profile</a>
        </nav>
    </div>
</div>

{% block content %}
    Contents
{% endblock content%}

</body>
</html>

src/templates/base_form.html
{% load crispy_forms_tags %}

{# This Form style is Card, and has parameter 'title' and 'width' #}
<div class="card">
    <div class="card-header fw-bold text-center">{{ title }}</div>
    <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-success mt-3 float-end" type="submit">{{ title }}</button>
        </form>
    </div>
</div>

src/templates/base_layout.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>SNS Project</title>
</head>

<body>

<!-- Message Info -->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}"> {{ message }} </div>
    {% endfor %}
{% endif %}

<div class="container my-3">
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
            <span class="fs-4">Social Network App</span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <!-- Login User Info -->
            {% if user.is_authenticated %}
                <a class="me-1 py-2 link-body-emphasis text-decoration-none" href="{% url 'posts:post_list' %}?username={{ user.username }}">
                    {% if user.profile_image %}
                        <img src="/media/{{ user.profile_image }}" height="30px" style="border-radius: 50%;">
                    {% endif %}
                    {{ user }}
                </a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'logout' %}" style="color: gray">(Logout)</a>
            {% endif %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Search</a>
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Feed</a>
        </nav>
    </div>
</div>

{% block content %}
{% endblock content %}

</body>
</html>

src/templates/sidebar.html
<div class="container d-flex justify-content-end">
    <div class="btn-group">
        <a href="{% url "posts:post_create" %}" class="btn btn-primary">새 포스팅</a>
        <a href="{% url 'profile_edit' %}" class="btn btn-secondary" style="text-decoration: none">프로필수정</a></a>
        <a href="{% url 'password_change' %}" class="btn btn-secondary" style="text-decoration: none">비밀번호변경</a>
    </div>

</div>

<div class="card my-3">
    <div class="card-header text-center">
        <b>My</b>
    </div>
    <div class="card-body">
        <p>Total upload posting : {{ post_list.count }}</p>
        <hr>
        <p>{{ user.bio|linebreaksbr }}</p>
        <p>(Website URL) {{ user.website_url }}</p>
        <p>(Email) {{ user.email }}</p>
        <hr>
        <p>
            My tags :
            {{ user_tags_all.items }}
            {% for tag_name, tag_count in user_all_tags.items %}
                <span>
                    <a href="{% url 'posts:post_list' %}?username={{ user.username }}&tag={{ tag_name }}"
                       style="text-decoration: none">
                        #{{ tag_name }}({{ tag_count }})
                    </a>
                </span>
            {% endfor %}
        </p>
    </div>
</div>