src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(RedirectView.as_view(url='posts/')), name='root'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Debug-toolbar setting
    import debug_toolbar
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

src/posts/urls.py
from django.urls import path

from . import views
from .views import PostListView

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
    path('update/<int:id>/', views.post_update, name='post_update'),
]

src/posts/models.py
from collections import Counter

from django.db import models
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager


def photo_upload_path(instance, filename):
    return f'posts/{instance.author.id}/{filename}'


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampMixin, models.Model):
    class Meta:
        ordering = ['-created_at']

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=photo_upload_path)
    caption = models.TextField(max_length=500)
    location = models.CharField(max_length=100, blank=True)

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('posts: post_detail', args=[self.id])

    def is_author(self, request):
        return request.user.id is self.author.id

    @classmethod
    def get_all_tag_counts_by_author(cls, author) -> dict:
        tags = []
        post_qs = Post.objects.select_related('author').filter(author=author).prefetch_related('tags')
        for post in post_qs:
            tags += [tag.name for tag in post.tags.all()]
        tag_counter = Counter(tags)
        return dict(tag_counter)


class Comment(TimeStampMixin, models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    body = models.TextField(max_length=500)

src/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location', 'tags']

src/posts/views.py
from django.contrib import messages
from django.db.models import QuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import Post, PostForm


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/post_list.html'

    def get_context_data(self, *args, **kwargs):
        user_all_tags = Post.get_all_tag_counts_by_author(author=self.request.user)
        context = super().get_context_data(*args, **kwargs)
        context['user_all_tags'] = user_all_tags
        return context

    def get_queryset(self) -> QuerySet:
        username = self.request.GET.get('username')
        tag = self.request.GET.get('tag')
        qs = super().get_queryset()
        if username:
            qs = qs.filter(author__username=username)
            if tag:
                qs = qs.filter(tags__name__contains=tag)
            return qs
        return qs


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            messages.success(request, "포스팅을 생성하였습니다.")
            return redirect('/')
    else:
        form = PostForm()
    return render(request, 'posts/post_create_form.html', {'form': form})


@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if post.is_author(request):
        post.photo.delete()
        post.delete()
        messages.success(request, '삭제 되었습니다.')
    else:
        messages.warning(request, '삭제 권한이 없습니다.')
    return redirect('posts:post_list')


@login_required
def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    if post.is_author(request):
        if request.method == 'POST':
            form = PostForm(data=request.POST, instance=post)
            if form.is_valid():
                messages.success(request, '수정 하였습니다.')
                form.save()
        else:
            form = PostForm(instance=post)
            return render(request, 'posts/post_update_form.html', context={'form': form})
    messages.warning(request, '수정 권한이 없습니다.')
    return redirect('posts:post_list')

src/templates/posts/post_create_form.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-sm-4">
            {% include 'base_form.html' with title='Add Posting' %}
        </div>
    </div>
{% endblock %}

src/templates/posts/post_detail.html
<script>
    function deleteConfirm(url) {
        const state = confirm("삭제 하시겠습니까?");
        if (state) {
            location.href = url;
        }
    }
</script>

<div class="card">
    <!-- CARD HEADER -->
    <div class="card-header" style="background-color: #87AFEB">
        <span style="font-style: italic; color: aliceblue;">
            Posted at {{ post.created_at|date }} by
            <a href="{% url 'posts:post_list' %}"
               style="text-decoration: none">{{ post.author.username }}</a>
        </span>
        {% if post.created_at != post.updated_at %}
            <span class="float-end" style="font-size:15px; color:#c8c8c8 ">수정됨</span>
        {% endif %}
        {% if user == post.author %}
            <div class="btn-group float-end">
                <a href="{% url 'posts:post_update' post.id %}" class="btn btn-group btn-primary">수정</a>
                <button class="btn btn-group btn-danger"
                        onclick="deleteConfirm('{% url "posts:post_delete" post.id %}')">삭제
                </button>
            </div>
        {% endif %}
    </div>
    <!-- CARD BODY -->
    <div class="card-body">
        <div class="row justify-content-center">
            <img src="/media/{{ post.photo }}" style="width: fit-content; border-radius: 3%">
        </div>
        <div class="row">
            <p class="pt-3">{{ post.caption|linebreaksbr }}</p>
        </div>
    </div>
    <!-- CARD FOOTER -->
    {% if post.tags.all %}
        <div class="card-footer" style="background-color: #EBF5FF">
            {% for tag in post.tags.all %}
                <a href="#" style="text-decoration: none"><span
                        style="font-weight: bolder; ">#{{ tag }}</span></a>
            {% endfor %}
        </div>
    {% endif %}
</div>

src/templates/posts/post_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 ms-5 my-2">
                {% for post in post_list %}
                    <div class="my-3">
                        {% include "posts/post_detail.html" with post=post %}
                    </div>
                {% endfor %}
            </div>
            <div class="col">
                {% include 'sidebar.html' %}
            </div>
        </div>
    </div>


{% endblock %}

src/templates/posts/post_update_form.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-sm-4">
            {% include 'base_form.html' with title='Update Post' %}
        </div>
    </div>
{% endblock %}